CC?=gcc
ifeq "$(WIN)" "64"
    CFLAGS+=-m64 -std=gnu99 -O3 -Wall -DWIN32
else
    CFLAGS+=-m32 -std=gnu99 -O3 -Wall -DWIN32
endif

all: nvimclient.exe nvimserver.exe

nvimclient.exe: nvimclient.c
	$(CC) $(CFLAGS) nvimclient.c -lWs2_32 -o nvimclient

nvimserver.exe: nvimserver.c
	$(CC) $(CFLAGS) nvimserver.c -lWs2_32 -o nvimserver

clean:

