CC?=gcc
ifeq "$(WIN)" "64"
    CFLAGS+=-m64 -std=gnu99 -O3 -Wall -DWIN32
else
    CFLAGS+=-m32 -std=gnu99 -O3 -Wall -DWIN32
endif

all: nvimrclient.exe nvimrserver.exe

nvimrclient.exe: nvimrclient.c
	$(CC) $(CFLAGS) nvimrclient.c -lWs2_32 -mwindows -o nvimrclient

nvimrserver.exe: nvimrserver.c
	$(CC) $(CFLAGS) nvimrserver.c -lWs2_32 -o nvimrserver

clean:

